### ISSUE TITLE
initial todo

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityLauncherAvalonia#1]
- [ ] setup project
- [ ] build UI (mainwindow, tabs, datagrids or similar, buttons, checkboxes, toggles, inputfields..)
- [ ] setup component styles (doesn't have to be 100% same, but just to get overview view of how it looks with avalonia components)
- [ ] test in mac
- [ ] continue with features (order: from important to less important, ie. get project list, get installed editors, open project..)

**Comment by unitycoder** [comment]
@muveso if you know how to setup initial project, feel free to commit (i'm still checking those getting started stuff today)

**Comment by muveso** [comment]
In Rider, there is an Avalonia plugin already. I recommend it; I will create an initial project with it. After the setup, I need to fetch some significant features from the other repo and continue to develop.

**Comment by unitycoder** [comment]
ok i dont have rider, but there is some vs studio plugin also, but go ahead for setup.

even before features, could try building those UI elements and tabs, buttons, so see how it looks,
and to check how the build runs on win, macos machines.
